common/models/Author.php
<?php

namespace common\models;

use Yii;
use yii\db\Query;

/**
 * This is the model class for table "author".
 *
 * @property integer $id
 * @property string $surname
 * @property string $name
 * @property string $middlename
 *
 * @property BookAuthor[] $bookAuthors
 * @property Book[] $books
 */
class Author extends \yii\db\ActiveRecord
{

    /**
     * var string Полное имя автора
     * */
    private $_fullName;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'author';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['surname', 'name'], 'required'],
            [['surname', 'name', 'middlename'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'surname' => 'Фамилия',
            'name' => 'Имя',
            'middlename' => 'Отчество',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBookAuthors()
    {
        return $this->hasMany(BookAuthor::className(), ['author_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBooks()
    {
        return $this->hasMany(Book::className(), ['id' => 'book_id'])->viaTable('book_author', ['author_id' => 'id']);
    }

    /**
     * @inheritdoc
     * @return \common\models\query\AuthorQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\AuthorQuery(get_called_class());
    }


    public function getFullName(){
        return $this->surname.' '.$this->name. ($this->middlename ? ' '.$this->middlename : '');
    }
}

frontend/controllers/AuthorController.php
<?php
/**
 * Created by PhpStorm.
 * User: sz
 * Date: 04.03.16
 * Time: 18:03
 */

namespace frontend\controllers;


use common\models\Author;
use frontend\models\form\AuthorForm;
use frontend\models\search\AuthorReportSearch;
use yii\bootstrap\ActiveForm;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\web\Response;
use yii\web\ServerErrorHttpException;
use Yii;

class AuthorController extends FrontendController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['index', 'view', 'report'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['create', 'update', 'delete'],
                        'roles' => ['@']
                    ],
                    [
                        'allow' => false,
                        'roles' => ['*']
                    ],
                ]
            ]
        ];
    }

    public function actionIndex(){
        $dataProvider = new ActiveDataProvider([
            'query' => Author::find()
        ]);
        return $this->render('index', [
            'dataProvider' => $dataProvider
        ]);
    }

    public function actionReport(){
        $model = new AuthorReportSearch();
        $dataProvider = $model->search(Yii::$app->getRequest()->get());
        return $this->render('report', [
            'dataProvider' => $dataProvider,
            'model' => $model,
        ]);
    }


    public function actionView($id){
        $model = $this->findModel($id);
        return $this->render('view', [
            'model' => $model,
        ]);
    }

    public function actionCreate(){
        $model = new Author();

        if($model->load(\Yii::$app->getRequest()->post())){
            $this->ajaxValidate($model);
            if($model->save()){
                return $this->redirect(['view', 'id'=>$model->id]);
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    public function actionUpdate($id){
        $model = $this->findModel($id);

        if($model->load(\Yii::$app->getRequest()->post())){
            $this->ajaxValidate($model);
            if($model->save()){
                return $this->redirect(['view', 'id'=>$model->id]);
            }
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    public function actionDelete($id){
        $model = $this->findModel($id);
        if($model->delete()){
            return $this->redirect(['index']);
        }
        else{
            throw new ServerErrorHttpException('Failed to delete the object for unknown reason.');
        }
    }

    public function findModel($id){
        return parent::_findModel(Author::className(), $id);
    }
} 

frontend/views/author/_form.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;
use yii\helpers\ArrayHelper;
?>
<?php $form = ActiveForm::begin([
    'options' => [
        'id' => 'author_form',
        'enctype' => 'multipart/form-data',
    ]
]); ?>

    <div class="row">
        <div class="col-sm-6">
            <?= $form->field($model, 'surname')?>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <?= $form->field($model, 'name')?>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <?= $form->field($model, 'middlename')?>
        </div>
    </div>

<?= Html::submitButton('Сохранить',
    [
        'class' => $model->isNewRecord ? 'btn btn-primary btn-large' : 'btn btn-success btn-large'
    ]
) ?>
<?php ActiveForm::end(); ?>

frontend/views/author/_reportForm.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;
use yii\helpers\ArrayHelper;
?>
<?php $form = ActiveForm::begin([
    'options' => [
        'id' => 'author_form',
    ],
    'method' => 'get'
]); ?>

    <div class="row">
        <div class="col-md-6">
            <?= $form->field($model, 'year')?>
        </div>
    </div>

<?= Html::submitButton('Найти',
    [
        'class' => 'btn btn-success btn-large'
    ]
) ?>
<?php ActiveForm::end(); ?>

frontend/views/author/create.php
<?php

$this->title = 'Авторы';
$this->params['subtitle'] = 'Создание';
$this->params['breadcrumbs'] = [
    [
        'label' => $this->title,
        'url' => ['index'],
    ],
    $this->params['subtitle']
]; ?>
<div class="row">
    <div class="col-sm-12">
        <?
        echo $this->render(
            '_form',
            [
                'model' => $model,
            ]
        );?>
    </div>
</div>

frontend/views/author/index.php
<?
use yii\grid\GridView;
use yii\grid\CheckboxColumn;
use yii\grid\ActionColumn;
use yii\bootstrap\Html;
use yii\helpers\Url;

$gridId = 'book-list';

$gridConfig = [
    'id' => $gridId,
    'dataProvider' => $dataProvider,
    'columns' => [
        [
            'class' => CheckboxColumn::classname()
        ],
        'surname', 'name', 'middlename',
    ]
];
if(!Yii::$app->user->isGuest){
    $actions[] = '{update}';
    $actions[] = '{delete}';
    $gridConfig['columns'][] = [
        'class' => ActionColumn::className(),
        'template' => implode(' ', $actions),
    ];
}
?>
<?if(!Yii::$app->user->isGuest){
    echo Html::a('Создать', Url::to(['author/create']),
        [
            'class' => 'btn btn-primary btn-large'
        ]
    );
} ?>
<div class="row">
    <div class="col-xs-12">
        <?=  GridView::widget($gridConfig);?>
    </div>
</div>

frontend/views/author/report.php
<?
use yii\grid\GridView;
use yii\grid\CheckboxColumn;
use yii\bootstrap\Html;

$gridId = 'author-list';
$gridConfig = [
    'id' => $gridId,
    'dataProvider' => $dataProvider,
    'columns' => [
        [
            'class' => CheckboxColumn::classname()
        ],
        [
            'attribute'=>'surname',
            'format'=>'raw',
            'value' => function($data){
                return Html::a($data->surname, ['author/view', 'id'=>$data->id]);
            },
        ],
        'name', 'middlename',
        [
            'attribute' => 'booksCnt',
        ],
    ]
];
?>

<div class="row">
    <div class="col-xs-4">
        <?= $this->render('_reportForm', [
            'model' => $model,
        ]);?>
    </div>
    <div class="col-xs-12">
        <?=  GridView::widget($gridConfig);?>
    </div>
</div>

frontend/views/author/update.php
<?php
use backend\widgets\spaceImage\SpaceImageWidget;
use backend\web\theme\widgets\Box;

$this->title = 'Автор '.$model->getFullName();
$this->params['breadcrumbs'] = [
    $this->title
];
?>
<div class="row">
    <div class="col-sm-12">
        <?php
        echo $this->render(
            '_form',
            [
                'model' => $model,
            ]
        );?>
    </div>
</div>

frontend/views/author/view.php
<?php
/**
 * Created by PhpStorm.
 * User: sz
 * Date: 05.03.16
 * Time: 12:10
 */

use yii\widgets\DetailView;

$this->title = 'Автор '.$model->getFullName();
$this->params['breadcrumbs'] = [
    $this->title
];

$attributes = [
    'surname', 'name', 'middlename'
];

echo DetailView::widget([
    'model'=>$model,
    'attributes'=>$attributes,
]);