common/models/Book.php
<?php

namespace common\models;

use Yii;
use yii\bootstrap\Html;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\helpers\VarDumper;

/**
 * This is the model class for table "book".
 *
 * @property integer $id
 * @property string $title
 * @property integer $year
 * @property string $description
 * @property string $isbn
 * @property string $image
 *
 * @property BookAuthor[] $bookAuthors
 * @property Author[] $authors
 */
class Book extends \yii\db\ActiveRecord
{
    public $img;

    protected $_imagePath;
    private $_authorNames;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'book';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'year', 'isbn'], 'required'],
            [['year'], 'integer'],
            [['description'], 'string'],
            [['title', 'isbn'], 'string', 'max' => 255],
            [['isbn'], 'unique', 'filter' => function($query){
                if(!$this->isNewRecord)
                    $query->andWhere(['<>', 'book.id', $this->id]);
            }],
            [['authorNames'], 'safe'],
            [['img'], 'file', 'mimeTypes'=> ['image/png', 'image/jpeg', 'image/gif'], 'wrongMimeType' => 'Недопустимый тип файла'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Название',
            'year' => 'Год выпуска',
            'description' => 'Описание',
            'isbn' => 'Isbn',
            'image' => 'Обложка',
            'authorNames' => 'Авторы',
        ];
    }

    public function beforeSave($insert){
        if(parent::beforeSave($insert)){
            if($this->img){
                $this->img->name = uniqid() . '.' . $this->img->extension;
                $this->image = $this->img->name;
                if(!$this->img->saveAs($this->getImagePath() . $this->img->name))
                    return false;
            }
            return true;
        }
        return false;
    }

    public function afterSave($insert, $changedAttributes){
        parent::afterSave($insert, $changedAttributes);
        $this->saveAuthors($this->authorNames);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBookAuthors()
    {
        return $this->hasMany(BookAuthor::className(), ['book_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAuthors()
    {
        return $this->hasMany(Author::className(), ['id' => 'author_id'])->viaTable('book_author', ['book_id' => 'id']);
    }

    /**
     * @inheritdoc
     * @return \common\models\query\BookQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\BookQuery(get_called_class());
    }

    public function getImagePath(){
        return \Yii::getAlias('@statics').'/web/images/';
    }

    public function getImageSrc($image){
        if(!file_exists($this->getImagePath(). '/' . $image) || !$image){
            return \Yii::getAlias('@web').'/images/default.jpg';
        }
        $imageDir = Yii::$app->getAssetManager()->publish($this->getImagePath());
        $fileName = \Yii::$app->getAssetManager()->getPublishedUrl($imageDir[0]). '/' . $image;
        return $fileName;
    }

    public function bookAuthorsLinks(){
        $authors = $this->authors;
        $return = '';
        if($authors){
            foreach($authors as $author){
                $return .= $return ? ',<br>' : '';
                $return .= Html::a($author->getFullName(), Url::to(['author/view', 'id'=>$author->id]));
            }
        }
        return $return;
    }


    public function getAuthorNames(){
        if($this->_authorNames)
            return $this->_authorNames;

        if($this->authors){
            return ArrayHelper::map($this->authors, 'id', 'id');
        }
    }
    public function setAuthorNames($authors){
        $this->_authorNames = $authors;
    }

    public function saveAuthors($authorKeys){
        $relatedKeys = [];

        foreach ($this->authors as $model) {
            $relatedKeys[] = $model->getPrimaryKey();
        }

        // удаляем отсутствующие в $orderKeys связи
        foreach (array_diff($relatedKeys, $authorKeys) as $id) {
            $model = Author::findOne($id);
            $this->unlink('authors', $model, true);
        }

        // добавляем новые связи
        foreach (array_diff($authorKeys, $relatedKeys) as $id) {
            $model = Author::findOne($id);
            $this->link('authors', $model);
        }
    }

}

frontend/controllers/BookController.php
<?php
/**
 * Created by PhpStorm.
 * User: sz
 * Date: 05.03.16
 * Time: 11:47
 */

namespace frontend\controllers;


use common\models\Book;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\helpers\VarDumper;
use yii\web\ServerErrorHttpException;
use yii\web\UploadedFile;

class BookController extends FrontendController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['index', 'view'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['create', 'update', 'delete'],
                        'roles' => ['@']
                    ],
                    [
                        'allow' => false,
                        'roles' => ['*']
                    ],
                ]
            ]
        ];
    }


    public function actionIndex(){
        $dataProvider = new ActiveDataProvider([
            'query' => Book::find()
        ]);
        return $this->render('index', [
            'dataProvider' => $dataProvider
        ]);
    }

    public function actionView($id){
        $model = $this->findModel($id);
        return $this->render('view', [
            'model' => $model,
        ]);
    }

    public function actionCreate(){
        $model = new Book();

        if($model->load(\Yii::$app->getRequest()->post())){
            $model->img = UploadedFile::getInstance($model, 'image');

            $this->ajaxValidate($model);
            if($model->save()){
                return $this->redirect(['view', 'id'=>$model->id]);
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    public function actionUpdate($id){
        $model = $this->findModel($id);

        if($model->load(\Yii::$app->getRequest()->post())){
            $model->img = UploadedFile::getInstance($model, 'image');

            $this->ajaxValidate($model);
            if($model->save()){
                return $this->redirect(['view', 'id'=>$model->id]);
            }

        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    public function actionDelete($id){
        $model = $this->findModel($id);
        if($model->delete()){
            return $this->redirect(['index']);
        }
        else{
            throw new ServerErrorHttpException('Failed to delete the object for unknown reason.');
        }
    }

    public function findModel($id){
        return parent::_findModel(Book::className(), $id);
    }
} 

frontend/views/book/_form.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;
use yii\helpers\ArrayHelper;
use common\models\Author;

?>
<?php $form = ActiveForm::begin([
    'options' => [
        'id' => 'book_form',
        'enctype' => 'multipart/form-data',
    ]
]); ?>
    <div class="row">
        <div class="col-sm-6">
            <?= $form->field($model, 'authorNames')->dropDownList(ArrayHelper::map(Author::find()->all(), 'id', 'fullName'), [
                'multiple' => true
            ])?>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <?= $form->field($model, 'title')?>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <?= $form->field($model, 'year')?>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <?= $form->field($model, 'description')->textarea()?>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <?= $form->field($model, 'isbn')?>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <?= $form->field($model, 'image')->fileInput()?>
        </div>
    </div>

<?= Html::submitButton('Сохранить',
    [
        'class' => $model->isNewRecord ? 'btn btn-primary btn-large' : 'btn btn-success btn-large'
    ]
) ?>
<?php ActiveForm::end(); ?>

frontend/views/book/create.php
<?php

$this->title = 'Книги';
$this->params['subtitle'] = 'Создание';
$this->params['breadcrumbs'] = [
    $this->title,
]; ?>
<div class="row">
    <div class="col-sm-12">
        <?
        echo $this->render(
            '_form',
            [
                'model' => $model,
            ]
        );?>
    </div>
</div>

frontend/views/book/index.php
<?
use yii\grid\GridView;
use yii\grid\CheckboxColumn;
use yii\grid\ActionColumn;
use yii\bootstrap\Html;
use yii\helpers\Url;

$gridId = 'book-list';

$gridConfig = [
    'id' => $gridId,
    'dataProvider' => $dataProvider,
    'columns' => [
        [
            'class' => CheckboxColumn::classname()
        ],
        [
            'attribute' => 'title',
            'format'=>'raw',
            'value' => function($data){
                return Html::a($data->title, Url::to(['book/view', 'id'=>$data->id]));
            },
        ],
        'year', 'isbn',
        [
            'attribute' => 'authorNames',
            'format'=>'raw',
            'value' => function($data){
                return $data->bookAuthorsLinks();
            },
        ],
    ]
];
if(!Yii::$app->user->isGuest){
    $actions[] = '{update}';
    $actions[] = '{delete}';
    $gridConfig['columns'][] = [
        'class' => ActionColumn::className(),
        'template' => implode(' ', $actions),
    ];
}
?>
<?if(!Yii::$app->user->isGuest){
    echo Html::a('Создать', Url::to(['book/create']),
        [
            'class' => 'btn btn-primary btn-large'
        ]
    );
} ?>
<div class="row">
    <div class="col-xs-12">
        <?=  GridView::widget($gridConfig);?>
    </div>
</div>

frontend/views/book/update.php
<?php
use backend\widgets\spaceImage\SpaceImageWidget;
use backend\web\theme\widgets\Box;

$this->title = 'Книга '.$model->title;
$this->params['breadcrumbs'] = [
    $this->title
];
?>
<div class="row">
    <div class="col-sm-12">
        <?php
        echo $this->render(
            '_form',
            [
                'model' => $model,
            ]
        );?>
    </div>
</div>

frontend/views/book/view.php
<?php
/**
 * Created by PhpStorm.
 * User: sz
 * Date: 05.03.16
 * Time: 12:10
 */

use yii\widgets\DetailView;
use yii\helpers\Html;

$this->title = 'Книга '.$model->title;
$this->params['breadcrumbs'] = [
    $this->title
];

$attributes = [
    'title', 'year', 'isbn',
    [
        'attribute'=>'authorNames',
        'format'=>'raw',
        'value' => $model->bookAuthorsLinks(),
    ],
    [
        'attribute'=>'image',
        'value'=>$model->getImageSrc($model->image),
        'format' => ['image',['width'=>'100','height'=>'100']],
    ]

];

echo DetailView::widget([
    'model'=>$model,
    'attributes'=>$attributes,
]);